sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "6"
before_install:
  - npm install
before_script:
  - npm prune
script:
  - npm run cover
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release