sudo: false
language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - "6"

install:
  - npm install -g codecov
  - npm install

before_script:
  - npm prune

script:
  - npm run cover
#  - npm run check-coverage
  - npm run report-coverage

after_success:
#  - npm run semantic-release

branches:
  only:
    - master